version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: aryan12032003/wanderlust-backend:latest
    container_name: wanderlust-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}

  frontend:
    build:
      context: ./frontend
    image: aryan12032003/wanderlust-frontend:latest
    container_name: wanderlust-frontend
    ports:
      - "3000:80"
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
